# Site settings
title: Hoot Dev
email: matthew.hootman@gmail.com
description: "Just a place to post thoughts on what I'm working on and learning in the world of web development."
baseurl: ""
url: "http://yourdomain.com"
github_username: hoot-dev

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-merlot
